# This is a basic workflow to help you get started with Actions
name: Python CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  scan:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]
    env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/agent/miniconda3/bin:/agent/java/jre/bin:/agent/maven/bin:/agent/sonar-scanner/sonar-scanner-4.6.0.2311-linux/bin
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Override git client provided in action from self-hosted runner.
      - name: Configure Git CLI (self hosted Runner)
        run: echo "/agent/miniconda3/bin/" >> $GITHUB_PATH

      - name: Display env variables in current workflow run.
        run: env

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone Repository
        uses: actions/checkout@v2.3.4

      # Display naming-convention used to onboard project in SonarQube.
      - name: Display github org/repo/branch
        run: echo ${{github.repository_owner}}-${{github.event.repository.name}}-${{github.head_ref}}
        # e.g.: santander-group-scib-oasis-lab-josemanuelcalvo-patch-2

      # Sonar-Scanner analyze src folder.
      - name: SonarQube analyzing
        run: sonar-scanner -Dsonar.host.url=${{secrets.SONAR_HOST_DEV}} -Dsonar.login=${{secrets.SONAR_TOKEN_DEV}} -Dsonar.projectKey=$PROJECT_KEY -Dsonar.projectBaseDir=$PROJECT_BASE_DIR -Dsonar.exclusions=$EXCLUSIONS
        env:
          PROJECT_KEY: ${{github.repository_owner}}-${{github.event.repository.name}}-${{github.head_ref}}
          PROJECT_BASE_DIR: "./src/"
          EXCLUSIONS: "./src/requirements.txt"

      - name: Clean Up job
        if: always()
        run: |
          echo Cleaning Workspace...
